import TaskReport from './TaskReport'
import Friends from './Friends'
import RecommandFD from './RecommandFD'
import MyInfo from './MyInfo'
import Login from './Login'
import Logout from './Logout'
import UserProfile from './UserProfile'
import SearchResult from './searchResult'
import Landing from './Landing'
import ViewProfile from './ViewProfile'
import ViewDivision from './ViewDivision'
import ChatUI from './ChatUI'
export { TaskReport, Friends, RecommandFD, MyInfo, Login, Logout, UserProfile, SearchResult, Landing,ViewProfile, ViewDivision,ChatUI }
